"""
formatter.py
────────────
Converts the accumulated CMAS JSON state (GraphState["json_state"]) into a
SOAP (Subjective / Objective / Assessment / Plan) clinical note.

The SOAP note is the final artifact handed to the physician after the
history-taking session concludes.
"""

from __future__ import annotations
from app.agent.state import CMASState


def _fmt_list(items: list | None, indent: int = 2) -> str:
    """Format a list of strings as a bulleted multi-line string."""
    if not items:
        return "  Not reported."
    pad = " " * indent
    return "\n".join(f"{pad}• {item}" for item in items)


def _fmt_symptoms(symptoms: list[dict] | None) -> str:
    """Format a list of SymptomSlot dicts into readable clinical text."""
    if not symptoms:
        return "  Not reported."
    lines = []
    for sym in symptoms:
        name = sym.get("value", "Unknown symptom")
        attrs = []
        for attr in ("onset", "duration", "severity", "location", "progression", "frequency"):
            val = sym.get(attr)
            if val:
                attrs.append(f"{attr}: {val}")
        attr_str = f" ({'; '.join(attrs)})" if attrs else ""
        lines.append(f"  • {name.capitalize()}{attr_str}")
    return "\n".join(lines)


def build_soap_note(json_state: CMASState) -> str:
    """
    Build a formatted SOAP note string from the CMAS JSON state.

    Parameters
    ----------
    json_state : CMASState
        The structured slot data accumulated during the session.

    Returns
    -------
    str
        A multi-line plain-text SOAP note suitable for display in a UI or
        storage in an EMR.
    """
    # ── Subjective ────────────────────────────────────────────────────────────
    chief = json_state.get("chief_complaint") or "Not specified."
    pos_symptoms = _fmt_symptoms(json_state.get("positive_symptoms"))
    neg_symptoms = _fmt_symptoms(json_state.get("negative_symptoms"))

    # ── History / Habits ──────────────────────────────────────────────────────
    pmh = _fmt_list(json_state.get("patient_medical_history"))
    fmh = _fmt_list(json_state.get("family_medical_history"))
    meds = _fmt_list(json_state.get("medications"))
    tests = _fmt_list(json_state.get("medical_tests"))
    exposures = _fmt_list(json_state.get("exposures"))

    habits_raw: dict = json_state.get("habits") or {}
    habits_lines = [f"  • {k.capitalize()}: {v}" for k, v in habits_raw.items()] or ["  Not reported."]
    habits = "\n".join(habits_lines)

    basic: dict = json_state.get("basic_information") or {}
    patient_info = ", ".join(f"{k}: {v}" for k, v in basic.items()) or "Not provided."

    # ── Note assembly ─────────────────────────────────────────────────────────
    note = f"""\
╔══════════════════════════════════════════════════════════╗
║           ANAM-AI  CLINICAL HISTORY  (SOAP NOTE)        ║
╚══════════════════════════════════════════════════════════╝

PATIENT INFORMATION
  {patient_info}

────────────────────────────────────────────────────────────
S U B J E C T I V E
────────────────────────────────────────────────────────────
Chief Complaint:
  {chief}

Positive Symptoms:
{pos_symptoms}

Negative Symptoms:
{neg_symptoms}

────────────────────────────────────────────────────────────
O B J E C T I V E
────────────────────────────────────────────────────────────
Past Medical History:
{pmh}

Family Medical History:
{fmh}

Current Medications:
{meds}

Medical Tests:
{tests}

Exposures:
{exposures}

Social / Habit History:
{habits}

────────────────────────────────────────────────────────────
A S S E S S M E N T
────────────────────────────────────────────────────────────
  [Physician to complete — AI history-taking agent does not diagnose.]

────────────────────────────────────────────────────────────
P L A N
────────────────────────────────────────────────────────────
  [Physician to complete — AI history-taking agent does not prescribe.]

════════════════════════════════════════════════════════════
  Generated by ANAM-AI History Taking Agent (MVP)
  ⚠  For physician review only — not a clinical diagnosis.
════════════════════════════════════════════════════════════
"""
    return note
